spring:
  application:
    name: Fornecedor
  datasource:
    url: jdbc:h2:mem:testdb
    username: usuario
    password: senha
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jdbc:
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update